version: "3.8"

x-logging: &default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

services:
  db:
    logging: *default-logging
    image: postgres:16.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./volumes/db/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    networks:
      - default
    

  web:
    logging: *default-logging
    build: 
      context: ./apps/shoponline
      dockerfile: dockerfile
    restart: unless-stopped
    networks:
      - default


  backend:
    logging: *default-logging
    build:
      context: ./apps/api-exc-shop
      dockerfile: dockerfile
    restart: unless-stopped
    networks:
      - default
   

volumes:
  db-data:

networks:
  default:


